chore: Remove commented out failing step in dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -33,9 +33,9 @@ jobs:
       run: dotnet build ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore
     - name: Test
       run: dotnet test ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj --no-build --verbosity normal
-    - name: Failing step
-      id: demo
-      run: exit 1
+    # - name: Failing step
+    #   id: demo
+    #   run: exit 1
     - name: failed job notification
       if: failure()
       run: echo "The job failed"
