chore: Update dotnet.yml to include Docker build and push steps

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -3,6 +3,8 @@
 
 name: .NET
 
+
+
 on:
   workflow_dispatch:
   push:
@@ -16,6 +18,10 @@ on:
   
 env:
     GH_TOKEN: ${{ secrets.GH_TOKEN }}
+    registryName: mhxwf75axzxruwthreg.azurecr.io
+    repositoryName: wth/dotnetcoreapp
+    dockerFolderPath: Application/src/RazorPagesTestSample
+    tag: ${{ github.run_number}}
 
 jobs:
   build:
@@ -35,10 +41,23 @@ jobs:
       run: dotnet build ./Application/src/RazorPagesTestSample/RazorPagesTestSample.csproj --no-restore
     - name: Test
       run: dotnet test ./Application/tests/RazorPagesTestSample.Tests/RazorPagesTestSample.Tests.csproj --no-build --verbosity normal
-    - name: Failing step
-      id: demo
-      run: exit 1
-    - name: failed job notification
-      if: failure()
-      run: |
-        gh issue create --title "Job failed" --body "Job failed for $GITHUB_SHA"
+    #- name: Failing step
+    #  id: demo
+    #  run: exit 1
+    #- name: failed job notification
+    #  if: failure()
+    #  run: |
+    #    gh issue create --title "Job failed" --body "Job failed for $GITHUB_SHA"
+
+  dockerJob:
+    runs-on: ubuntu-latest
+    steps:
+    - uses: actions/checkout@v2
+    - name: Docker Login
+      run: docker login $registryName -u ${secrets.ACR_USERNAME} -P ${secrets.ACR_PASSWORD}
+    - name: Docker Build
+      run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath
+    - name: Docker Push
+      run: docker push $registryName/$repositoryName:$tag
+
+    
